RefreshTokens:
  cron: '0 */4 * * *'
  class: RefreshTokens
  queue: collect
  description: 'Refreshes Access Tokens'
  
TestJob:
  cron: '0 0 5 31 2'
  class: TestJob
  queue: collect
  args: 
    'lejog testing'
  description: 'Just Testing the DB Connection'

# Loggeronly:
#   cron: '0 9 * * * *'
#   class: Alerter::Loggeronly
#   queue: loggeronly
#   args:
#     'testing rescue schedule alerter logger once per day'
#   description: 'Runs the perform method in Alerter::Loggeronly'